# Generated by Django 3.2.16 on 2023-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpimageresourcemock',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='httpimageresourcemock',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='httpresourcemock',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='httpresourcemock',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='microserviceresourcemock',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='microserviceresourcemock',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shellresourcemock',
            name='command',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='urlresourcemock',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='urlresourcemock',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
