# Generated by Django 4.2.29 on 2026-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydetailresource',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entityidlistresource',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entitylistresource',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='httpimageresourcemock',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='httpresourcemock',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='microserviceresourcemock',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='shellresourcemock',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='urlresourcemock',
            name='status',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
