language: python
install:
  - pip install tox
matrix:
  include:
    - name: "Django 1.11 (Python 3.5)"
      python: 3.5
      env:
       - TOX_ENV=django111
    - name: "Django 2.2 (Python 3.5)"
      python: 3.5
      env:
       - TOX_ENV=django22
    - name: "Django 1.11 (Python 3.6)"
      python: 3.6
      env:
       - TOX_ENV=django111
    - name: "Django 2.2 (Python 3.6)"
      python: 3.6
      env:
       - TOX_ENV=django22
    - name: "Django 1.11 (Python 3.7)"
      python: 3.7
      env:
       - TOX_ENV=django111
    - name: "Django 2.2 (Python 3.7)"
      python: 3.7
      env:
       - TOX_ENV=django22
script: tox -e $TOX_ENV
