language: python
install:
  - pip install tox
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
script: tox -e $TOX_ENV
services:
  - mysql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - DJANGO_POSTGRES_USER=postgres
  - DJANGO_MYSQL_USER=root
  matrix:
  - TOX_ENV=django111 DJANGO_DEFAULT_DATABASE=postgres
  - TOX_ENV=django111 DJANGO_DEFAULT_DATABASE=mysql
  - TOX_ENV=django22 DJANGO_DEFAULT_DATABASE=postgres
  - TOX_ENV=django22 DJANGO_DEFAULT_DATABASE=mysql
