# Generated by Django 4.2.29 on 2026-03-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0002_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='documents',
            field=models.ManyToManyField(related_name='+', through='datatypes.ProcessResult', to='datatypes.document'),
        ),
    ]
